[mypy]
python_version = 3.11
ignore_missing_imports = True
warn_unused_ignores = False
warn_return_any = False
disallow_untyped_defs = False
disallow_untyped_calls = False
disallow_incomplete_defs = False
check_untyped_defs = False
no_implicit_optional = False

[mypy-example.*]
ignore_errors = True

[mypy-nicegui.*]
ignore_errors = True

[mypy-sqlmodel.*]
ignore_errors = True